# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  dangerjs:
      docker:
        - image: circleci/node:10.15.3-jessie
      steps:
        - checkout
        - run:
            name: Install dependencies
            command: yarn install
        - run:
            name: Run DangerJS checks
            command: yarn danger:ci

workflows:
  version: 2
  only_danger:
    jobs:
      - dangerjs
