# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  test:
      working_directory: ~/test
      # The primary container is an instance of the first image listed. The job's commands run in this container.
      docker:
        - image: circleci/node:10.15.3-jessie
      steps:
        - checkout
        - run:
            name: Run tests
            command: npm run test

workflows:
  version: 2
  only_test:
    jobs:
      - test
